app/views/GM.py
#coding:utf-8
from flask import Blueprint, render_template, session, redirect, url_for
from ..models import userType

GM = Blueprint('GM', __name__)

#GM的根目錄
@GM.route('/')
def index():
   if session.get('userType') == userType['GM']:
      return redirect(url_for('GM.update_grade'))
   else:
      return redirect(url_for('GM.login'))

#忘記密碼頁面
@GM.route('/forgotPassword')
def forgot_password():
   return render_template('/GM/forgotPasswordGM.html')

#輸入新密碼頁面
@GM.route('/resetPassword/<token>')
def reset_password(token):
   return render_template('/GM/resetPasswordGM.html')

#登入頁面
@GM.route('/login')
def login():
   if session.get('userType') == userType['GM']:
      return redirect(url_for('GM.update_grade'))
   else:
      return render_template('/GM/loginGM.html')

#註冊頁面
@GM.route('/register')
def register():
   return render_template('/GM/registerGM.html')

#驗證頁面
@GM.route('/verify/<result>')
def verify(result):
   if result == '1':
      result_msg = '資料庫錯誤，請稍後再試'
   elif result == '2':
      result_msg = '資料庫錯誤，請稍後再試'
   elif result == '3':
      result_msg = '帳號驗證成功，等待管理員審核'
   elif result == '4':
      result_msg ='資料庫錯誤，請稍後再試'
   elif result == '5':
      result_msg = '帳號驗證成功，歡迎加入我們<br /><a href="' + url_for('GM.login') + '">點擊進入登入畫面</a>'
   elif result == '6':
      result_msg = '帳號已驗證成功，不需再次驗證'
   elif result == '7':
      result_msg = '帳號不在資料庫中，請重新申請'
   elif result == '8':
      result_msg = '帳號驗證失敗'
   elif result == 'TimeOut':
      result_msg = '網頁已過期，請重寄驗證信'
   else:
      result_msg = '網頁出現錯誤，請稍後再試'
   return result_msg

#評論審核
@GM.route('/updateGrade')
def update_grade():
   if session.get('userType') == userType['GM']:
      return render_template('/GM/updateGrade.html')
   else:
      return redirect(url_for('GM.login'))

#評論審核紀錄
@GM.route('/updateGradeRecord')
def update_grade_record():
   if session.get('userType') == userType['GM']:
      return render_template('/GM/updateGradeRecord.html')
   else:
      return redirect(url_for('GM.login'))

#檢舉審核
@GM.route('/reportApprove')
def report_approve():
   if session.get('userType') == userType['GM']:
      return render_template('/GM/reportApprove.html')
   else:
      return redirect(url_for('GM.login'))

#檢舉審核紀錄
@GM.route('/reportApproveRecord')
def report_approve_record():
   if session.get('userType') == userType['GM']:
      return render_template('/GM/reportApproveRecord.html')
   else:
      return redirect(url_for('GM.login'))

#設定頁面
@GM.route('/setting')
def setting():
   if session.get('userType') == userType['GM']:
      return render_template('/GM/settingGM.html')
   else:
      return redirect(url_for('GM.login'))

app/templates/GM/forgotPasswordGM.html
<!--GM忘記密碼-->
<!DOCTYPE html>
<html lang="zh-TW">

    <head>
        <title>忘記密碼</title>

        <meta charset="utf-8">
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        
        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/forgotPassword.css')}}">
    </head>

    <body>
        <header>
            <nav class="nav navbarBack">
                <div class="navbarContainer">
                    <div class="navbarLeft"></div>
                    <div class="navbarCenter">
                        <a class="navbarBrand">
                            <img class="navbarBrandImg" id="navbarBrandImg1" alt="TimeBank" src="{{url_for('static', filename='img/brandWhite.png')}}" />
                            <img class="navbarBrandImg" id="navbarBrandImg2" alt="TimeBank" src="{{url_for('static', filename='img/brandColor.png')}}" />
                        </a>
                    </div>
                    <div class="navbarRight"></div>
                </div>
            </nav>
        </header>
        <div class="bodyContainer">
            <div class="forgotPasswordDiv">
                <div class="formTitleDiv"><h3 id="formTitle">Manager 忘記密碼</h3></div>
                <div class="formColumn">
                    <div class="forgotPasswordUser" id="forgotPasswordUser">
                        <div class="formLine">
                            <div class="formLabelDiv"><label for="mail">電子郵件</label></div>
                            <input type="email" class="formText" id="userEmail" placeholder="輸入您的電子郵件" maxlength="50" autofocus />
                            <div id="emailError1" class="error">請輸入您的電子郵件(至多50字元)</div>
                            <div id="emailError2" class="error">電子郵件格式錯誤</div>
                            <div id="emailError3" class="error">無法找到對應的信箱，請確認您的電子郵件</div>
                            <div id="systemError1" class="error">系統錯誤，請稍後再試</div>
                            <div id="systemError2" class="error">重置信寄送失敗，請稍後再試</div>
                            <div id="systemError3" class="error">等待伺服器回應中...</div>
                        </div>
                        <div class="formLine">
                            <input type="submit" class="formButton" value="送 出" onclick="forgotPasswordEmail()" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="{{url_for('static', filename='js/forgotPasswordGM.js')}}"></script>
    </body>

</html>

app/templates/GM/loginGM.html
<!-- GM登入 -->
<!DOCTYPE HTML>
<html lang="zh-TW">

    <head>
        <title>登入 TimeBank</title>

        <meta charset="utf-8">
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        
        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/loginManager6.css')}}" type="text/css">
    </head>

    <body>
        <header>
            <nav class="nav navbarBack">
                <div class="navbarContainer">
                    <div class="navbarLeft">
                    </div>
                    <div class="navbarCenter">
                        <a class="navbarBrand" href="{{url_for('USER.index')}}">
                            <img class="navbarBrandImg" id="navbarBrandImg1" alt="TimeBank" src="{{url_for('static', filename='img/brandWhite.png')}}" />
                            <img class="navbarBrandImg" id="navbarBrandImg2" alt="TimeBank" src="{{url_for('static', filename='img/brandColor.png')}}" />
                        </a>
                    </div>
                    <div class="navbarRight">
                    </div>
                </div>
            </nav>
        </header>

        <div class="bodyContainer">
            <div class="loginDiv">
                <div class="formTitleDiv">
                    <h3 id="formTitle">登入</h3>
                </div>
                <div class="formColumn">
                    <div class="loginForm" id="loginFrom" name="loginForm">
                        <div style="margin: 0px 40px">
                            <div class="formLine">
                                <div class="formLabelDiv"><label for="gmName" class="formLabel">管理員名稱</label></div>
                                <input type="text" class="formText" id="adminName" name="gmName" placeholder="輸入您的使用者名稱" maxlength="20" onkeypress="if(event.keyCode == 13){gmLogin();}" />
                                <div id="error1" class="error wideError"></div>
                            </div>
                            <div class="formLine">
                                <div class="formLabelDiv"><label for="gmPassword" class="formLabel">密碼</label></div>
                                <input type="password" class="formText" id="adminPassword" name="gmPassword" placeholder="輸入您的密碼" maxlength="30" onkeypress="if(event.keyCode == 13){gmLogin();}" />
                                <div id="error0" class="error wideError"></div>
                            </div>
                            <div class="formLine" id="formLine2">
                                <input type="button" class="formButton" value="登入" onclick="gmLogin()">
                                <span class="psw"><a href="{{url_for('GM.forgot_password')}}">忘記密碼?</a></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="{{url_for('static', filename='js/loginGM.js')}}"></script>
    </body>
    
</html>

app/templates/GM/registerGM.html
<!--GM註冊-->
<!DOCTYPE html>
<html lang="zh-TW">

    <head>
        <title>加入我們 TimeBank</title>

        <meta charset="utf-8" />
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}" />
        <link rel="stylesheet" href="{{url_for('static', filename='css/register.css')}}" />
    </head>

    <body>
        <header>
            <nav class="nav navbarBack">
                <div class="navbarContainer">
                    <div class="navbarLeft"></div>
                    <div class="navbarCenter">
                        <a class="navbarBrand" href="{{url_for('USER.index')}}">
                            <img class="navbarBrandImg" id="navbarBrandImg1" alt="TimeBank" src="{{url_for('static', filename='img/brandWhite.png')}}" />
                            <img class="navbarBrandImg" id="navbarBrandImg2" alt="TimeBank" src="{{url_for('static', filename='img/brandColor.png')}}" />
                        </a>
                    </div>
                    <div class="navbarRight"></div>
                </div>
            </nav>
        </header>
        <div class="registerDiv">
            <div id="formTitleDiv"><h3 id="formTitle">加入我們</h3></div>
            <div class="formColumn">
                <div class="registerGM" id="registerGM" name="registerGM" onsubmit="return register()">
                    <div class="formLine">
                        <div class="formLabelDiv"><label for="gmName" class="formLabel">管理員名稱</label></div>
                        <input type="text" class="formText" id="gmName" name="gmName" placeholder="最多20字元，且不得與他人重複，無法修改" maxlength="20" />
                        <div id="error1" class="error"></div>
                    </div>

                    <div class="formLine">
                        <div class="formLabelDiv"><label for="gmPassword" class="formLabel">密碼</label></div>
                        <input type="password" class="formText" id="gmPassword" name="gmPassword" placeholder="8-30字元(含數字、大小寫字母及特殊符號)" maxlength="30" />
                        <div id="error2" class="error"></div>
                    </div>

                    <div class="formLine">
                        <div class="formLabelDiv"><label for="checkPassword" class="formLabel">確認密碼</label></div>
                        <input type="password" class="formText" id="checkPassword" name="checkPassword" placeholder="再次輸入密碼" maxlength="30" />
                        <div id="error3" class="error"></div>
                    </div>

                    <div class="formLine">
                        <div class="formLabelDiv"><label for="gmEmail" class="formLabel">電子郵件</label></div>
                        <input type="email" class="formText" id="gmEmail" name="gmEmail" placeholder="輸入您的電子郵件" maxlength="50" />
                        <div id="error4" class="error"></div>
                    </div>

                    <div class="formLine">
                        <div class="formLabelDiv"><label for="gmPhone" class="formLabel">電話號碼</label></div>
                        <input type="tel" class="formText" name="gmPhone" id="gmPhone" placeholder="輸入您的電話號碼" />
                        <div id="error5" class="error"></div>
                    </div>
                    <div class="formLine">
                        <input type="checkbox" id="gmTerms" />
                        <label for="gmTerms">已閱讀並同意<a href="#terms.html">管理員條款</a></label>
                        <div id="error0" class="error"></div>
                    </div>
                    <div class="formLine">
                        <input type="button" class="formButton" value="送出" onclick="gmRegister()" />
                        <input type="reset" class="formButton" value="重新填寫" onclick="window.location.reload()" />
                    </div>
                </div>
                <script src="{{url_for('static', filename='js/registerGM.js')}}"></script>
            </div>
        </div>
    </body>

</html>

app/templates/GM/reportApprove.html
<!--GM檢舉審核-->

<!DOCTYPE html>
<html lang="zh-TW">
    <head>
        <title>檢舉審核</title>

        <meta charset="utf-8" />
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/navbarManager.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/reportApprove.css')}}" type="text/css">

    </head>

    <body>
        <header id="GMnavbar"></header>
        <div class="bodyContainer">
            <div id="form">
                <div id="detail">
                    <div id="title">檢舉審核</div>
                    <div class="formLine">
                        <div class="auditButton">
                            <button id="formAudit">檢舉審核</button>
                            <a href="{{url_for('GM.report_approve_record')}}"><button id="formAudit">檢舉紀錄</button></a>
                        </div>
                    </div>
                    <div id="taskGradeDiv">
                        <div id="taskIDDiv">
                            <div id="taskLeft">檢舉編號<br><span id="reportID">1</span></div><!--
                        ---><div id="taskCenter">
                                <div class="taskInfo">檢舉時間：<span id="reportTime"></span></div>
                                <div class="taskInfo">檢舉人：<span id="reportUserName"></span></div>
                                <div class="taskInfo">檢舉原因：<span id="reportReason"></span></div>
                            </div><!--
                        ---><div id="taskRight">
                                <button class="button gradeButton" onclick="report(1)">已處理</button>
                                <button class="button gradeButton" onclick="report(2)">略過</button>
                            </div>
                        </div>
                        <div id="taskDetailDiv">
                            <div class="taskDetail">任務名稱：<span id="taskName"></span></div>
                            <div class="taskDetail">任務時間：<span id="taskTime"></span></div>
                            <div class="taskDetail">任務內容：<div><textarea class="textarea" id="taskContent" readonly></textarea></div></div>
                            <div class="taskDetail">雇主名稱：<span id="SRName"></span></div>
                            <div class="taskDetail">雇主電話號碼：<span id="SRPhone"></span></div>
                            <div class="taskDetail">雇主評分：<span id="SRRate"></span></div>
                            <div class="taskDetail">雇主評論：<div><textarea class="textarea" id="SRComment" readonly></textarea></div></div>
                            <div class="taskDetail">雇員名稱：<span id="SPName"></span></div>
                            <div class="taskDetail">雇員電話號碼：<span id="SPPhone"></span></div>
                            <div class="taskDetail">雇員評分：<span id="SPRate"></span></div>
                            <div class="taskDetail">雇員評論：<div><textarea class="textarea" id="SPComment" readonly></textarea></div></div>           
                        </div>
                    </div>
                    <div class="formPage">
                        <span id="formPage1">
                            <button class="button pageButton" id="prePageButton" onclick="computePage(1)">上一頁</button>
                            <span class="formPageNumber" id="pageNumber">1/1</span>
                            <button class="button pageButton" id="nextPageButton" onclick="computePage(2)">下一頁</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <script src="{{url_for('static', filename='js/clickToSpan.js')}}"></script>
        <script src="{{url_for('static', filename='js/navbarGM.js')}}"></script>
        <script src="{{url_for('static', filename='js/reportApprove.js')}}"></script>
    </body>
</html>

app/templates/GM/reportApproveRecord.html
<!--GM檢舉紀錄-->

<!DOCTYPE html>
<html lang="zh-TW">
    <head>
        <title>檢舉紀錄</title>

        <meta charset="utf-8" />
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/navbarManager.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/reportApprove.css')}}" type="text/css">

    </head>

    <body>
        <header id="GMnavbar"></header>
        <div class="bodyContainer">
            <div id="form">
                <div id="detail">
                    <div id="title">檢舉紀錄</div>
                    <div class="formLine">
                        <div class="auditButton">
                            <a href="{{url_for('GM.report_approve')}}"><button id="formAudit">檢舉審核</button></a>
                            <button id="formAudit">檢舉紀錄</button>
                        </div>
                    </div>
                    <div id="taskGradeDiv">
                        <div id="taskIDDiv">
                            <div id="taskLeft">檢舉編號<br><span id="reportID">1</span></div><!--
                        ---><div id="taskCenter">
                                <div class="taskInfo">檢舉時間：<span id="reportTime"></span></div>
                                <div class="taskInfo">檢舉人：<span id="reportUserName"></span></div>
                                <div class="taskInfo">檢舉原因：<span id="reportReason"></span></div>
                            </div><!--
                        ---><div id="taskRight">
                                <div class="taskInfo">結果：<span id="approveResult"></span></div>
                                <div class="taskInfo">gmID：<span id="gmID"></span></div>
                            </div>
                        </div>
                        <div id="taskDetailDiv">
                            <div class="taskDetail">任務名稱：<span id="taskName"></span></div>
                            <div class="taskDetail">任務時間：<span id="taskTime"></span></div>
                            <div class="taskDetail">任務內容：<div><textarea class="textarea" id="taskContent" readonly></textarea></div></div>
                            <div class="taskDetail">雇主名稱：<span id="SRName"></span></div>
                            <div class="taskDetail">雇主電話號碼：<span id="SRPhone"></span></div>
                            <div class="taskDetail">雇主評分：<span id="SRRate"></span></div>
                            <div class="taskDetail">雇主評論：<div><textarea class="textarea" id="SRComment" readonly></textarea></div></div>
                            <div class="taskDetail">雇員名稱：<span id="SPName"></span></div>
                            <div class="taskDetail">雇員電話號碼：<span id="SPPhone"></span></div>
                            <div class="taskDetail">雇員評分：<span id="SPRate"></span></div>
                            <div class="taskDetail">雇員評論：<div><textarea class="textarea" id="SPComment" readonly></textarea></div></div>           
                        </div>
                    </div>
                    <div class="formPage">
                        <span id="formPage1">
                            <button class="button pageButton" id="prePageButton" onclick="computePage(1)">上一頁</button>
                            <span class="formPageNumber" id="pageNumber">1/1</span>
                            <button class="button pageButton" id="nextPageButton" onclick="computePage(2)">下一頁</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <script src="{{url_for('static', filename='js/clickToSpan.js')}}"></script>
        <script src="{{url_for('static', filename='js/navbarGM.js')}}"></script>
        <script src="{{url_for('static', filename='js/reportApproveRecord.js')}}"></script>
    </body>
</html>

app/templates/GM/resetPasswordGM.html
<!--GM輸入新密碼-->
<!DOCTYPE html>
<html lang="zh-TW">

    <head>
        <title>忘記密碼</title>

        <meta charset="utf-8">
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        
        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/forgotPassword.css')}}">
    </head>

    <body>
        <header>
            <nav class="nav navbarBack">
                <div class="navbarContainer">
                    <div class="navbarLeft"></div>
                    <div class="navbarCenter">
                        <a class="navbarBrand">
                            <img class="navbarBrandImg" id="navbarBrandImg1" alt="TimeBank" src="{{url_for('static', filename='img/brandWhite.png')}}" />
                            <img class="navbarBrandImg" id="navbarBrandImg2" alt="TimeBank" src="{{url_for('static', filename='img/brandColor.png')}}" />
                        </a>
                    </div>
                    <div class="navbarRight"></div>
                </div>
            </nav>
        </header>
        <div class="bodyContainer">
            <div class="newPasswordDiv">
                <div class="formTitleDiv"><h3 id="formTitle">輸入新密碼</h3></div>
                <div class="formColumn">
                    <div class="newPasswordUser">
                        <div class="formLine">
                            <div class="formLabelDiv"><label for="newPassword">新密碼</label></div>
                            <input type="password" class="formText" id="newPassword" placeholder="8-30字元(含數字、大小寫字母及特殊符號)" maxlength="30" autofocus onkeypress="if(event.keyCode == 13){resetPassword();}"/>
                            <div id="passwordError1" class="error">請輸入密碼，至多30字元</div>
                            <div id="passwordError2" class="error">密碼格式不符，請再試一次</div>
                        </div>
                        <div class="formLine">
                            <div class="formLabelDiv"><label for="checkPassword">確認新密碼</label></div>
                            <input type="password" class="formText" id="checkPassword" name="checkPassword"  placeholder="再次輸入新密碼" maxlength="30" />
                            <div id="passwordError3" class="error">請再次輸入您的密碼</div>
                            <div id="passwordError4" class="error">密碼不相符，請再試一次</div>
                            <div id="systemError1" class="error">系統錯誤，請稍後再試</div>
                            <div id="systemError2" class="error">等待伺服器回應中...</div>
                        </div>
                        <div class="formLine"><input type="submit" class="formButton" value="送 出" onclick="resetPassword()"></div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
        <script src="{{url_for('static', filename='js/resetPasswordGM.js')}}"></script>
    </body>

</html>

app/templates/GM/updateGrade.html
<!--GM評論審核-->

<!DOCTYPE html>
<html lang="zh-TW">
    <head>
        <title>評論審核</title>

        <meta charset="utf-8" />
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/navbarManager.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/updateGrade.css')}}" type="text/css">

    </head>

    <body>
        <header id="GMnavbar"></header>
        <div class="bodyContainer">
            <div id="form">
                <div id="detail">
                    <div id="title">評論審核</div>
                    <div class="formLine">
                        <div class="auditButton">
                            <button id="formAudit">評論審核</button>
                            <a href="{{url_for('GM.update_grade_record')}}"><button id="formAudit">評論紀錄</button></a>
                        </div>
                    </div>
                    <div id="taskGradeDiv">
                        <div id="taskIDDiv">
                            <div id="taskLeft">任務編號<br><span id="taskID">1</span></div><!--
                        ---><div id="taskCenter">
                                <div class="taskInfo">任務時間：<span id="taskTime"></span></div>
                                <div class="taskInfo">任務名稱：<span id="taskName"></span></div>
                                <div class="taskInfo">雇主評分：<span id="SRRate"></span></div>
                                <div class="taskInfo">雇員評分：<span id="SPRate"></span></div>
                            </div><!--
                        ---><div id="taskRight">
                                <button class="button gradeButton" onclick="grade('1')">確 認</button>
                                <button class="button gradeButton" onclick="grade('0')">否 決</button>
                            </div>
                        </div>
                        <div id="taskDetailDiv">
                            <div class="taskDetail">任務內容：<div><textarea class="textarea" id="taskContent" readonly></textarea></div></div>
                            <div class="taskDetail">雇主名稱：<span id="SRName"></span></div>
                            <div class="taskDetail">雇主電話號碼：<span id="SRPhone"></span></div>
                            <div class="taskDetail">雇主評論：<div><textarea class="textarea" id="SRComment" readonly></textarea></div></div>
                            <div class="taskDetail">雇員名稱：<span id="SPName"></span></div>
                            <div class="taskDetail">雇員電話號碼：<span id="SPPhone"></span></div>
                            <div class="taskDetail">雇員評論：<div><textarea class="textarea" id="SPComment" readonly></textarea></div></div>
                        </div>
                    </div>
                    <div class="formPage">
                    	<div class="formPage1">
                    		<span id="formPage1">
	                            <button class="button pageButton" id="prePageButton" onclick="computePage(1)">上一頁</button>
	                            <span class="formPageNumber" id="pageNumber">1/1</span>
	                            <button class="button pageButton" id="nextPageButton" onclick="computePage(2)">下一頁</button>
	                        </span>
                    	</div>
                        <div class="formPage2">
                        	<span class="allGradeButtonSpan" id="formPage2">
	                            <button class="button allGradeButton" onclick="gradeAll('1')">全 部 確 認</button>
	                            <button class="button allGradeButton" id="allGradeButton1" onclick="gradeAll('0')">全 部 否 決</button>
	                        </span>
                        </div>                       
                    </div>
                </div>
            </div>
        </div>

        <script src="{{url_for('static', filename='js/clickToSpan.js')}}"></script>
        <script src="{{url_for('static', filename='js/navbarGM.js')}}"></script>
        <script src="{{url_for('static', filename='js/updateGrade.js')}}"></script>
    </body>
</html>