app/controllers/calendar.py
#coding: utf-8
from flask import Blueprint, jsonify, request, session
from ..models.model import *
from ..models import userType
import datetime

Calendar = Blueprint('calendar', __name__)

days_of_month = {1: 31, 3: 31, 4: 30, 5: 31, 6: 30, 7: 31,\
                8: 31, 9: 30, 10: 31, 11: 30, 12: 31}

#取得當月行事曆
@Calendar.route('/one_month_list', methods=['POST'])
def one_month_list():
    if request.method == 'POST':
        if session.get('userType') == userType['USER']:
            try:
                value = request.get_json()
            except:
                return jsonify({"rspCode": 40})                                                                          #非法文字
            show_year = value['year']
            show_month = value['month']
            userID = session.get('userID')
            if show_month < 1 or show_month > 12:
                return jsonify({"rspCode": 41})                                                                          #月份錯誤
            try:
                query_data = account.query.filter_by(userID = userID).first()
                if query_data == None:
                    return jsonify({"rspCode": 42})                                                                      #沒有該user
            except:
                return jsonify({"rspCode": 30})                                                                          #資料庫錯誤
            if show_month != 2:
                days = days_of_month[show_month]
            else:
                if show_year % 4 == 0:
                    if show_year % 100 == 0:
                        days = 29
                    else:
                        days = 28
                else:
                    days = 28
            dateList = []
            for day in range(1, days + 1):
                dateStart = datetime.datetime(show_year, show_month, day, 0, 0, 0)
                dateEnd = datetime.datetime(show_year, show_month, day, 23, 59, 59)
                Found = False
                for task in query_data.taskSR:
                    #確定不是取消跟刪除
                    if task.taskStatus != 4 and task.taskStatus != 11 and task.taskStatus != 12:
                        if dateStart > task.taskStartTime and dateStart < task.taskEndTime:
                            dateList.append(1)
                            Found = True
                            break
                        elif dateEnd > task.taskStartTime and dateEnd < task.taskEndTime:
                            dateList.append(1)
                            Found = True
                            break
                        elif dateStart < task.taskStartTime and dateEnd > task.taskStartTime:
                            dateList.append(1)
                            Found = True
                            break
                        elif dateStart < task.taskStartTime and dateEnd > task.taskEndTime:
                            dateList.append(1)
                            Found = True
                            break
                if not Found:
                    for taskCandidate_ in query_data.db_account_taskCandidate:
                        #還在申請中
                        if taskCandidate_.task.taskStatus == 1:
                            if dateStart > taskCandidate_.task.taskStartTime and dateStart < taskCandidate_.task.taskEndTime:
                                dateList.append(1)
                                Found = True
                                break
                            elif dateEnd > taskCandidate_.task.taskStartTime and dateEnd < taskCandidate_.task.taskEndTime:
                                dateList.append(1)
                                Found = True
                                break
                            elif dateStart < taskCandidate_.task.taskStartTime and dateEnd > taskCandidate_.task.taskStartTime:
                                dateList.append(1)
                                Found = True
                                break
                            elif dateStart < taskCandidate_.task.taskStartTime and dateEnd > taskCandidate_.task.taskEndTime:
                                dateList.append(1)
                                Found = True
                                break
                        #已經接到或是完成
                        elif taskCandidate_.task.taskStatus > 1 and taskCandidate_.task.taskStatus != 4 and taskCandidate_.task.taskStatus != 11 and taskCandidate_.task.taskStatus != 12:
                            #確定SP是自己
                            if taskCandidate_.task.SP[0].userID == userID:
                                if dateStart > taskCandidate_.task.taskStartTime and dateStart < taskCandidate_.task.taskEndTime:
                                    dateList.append(1)
                                    Found = True
                                    break
                                elif dateEnd > taskCandidate_.task.taskStartTime and dateEnd < taskCandidate_.task.taskEndTime:
                                    dateList.append(1)
                                    Found = True
                                    break
                                elif dateStart < taskCandidate_.task.taskStartTime and dateEnd > taskCandidate_.task.taskStartTime:
                                    dateList.append(1)
                                    Found = True
                                    break
                                elif dateStart < taskCandidate_.task.taskStartTime and dateEnd > taskCandidate_.task.taskEndTime:
                                    dateList.append(1)
                                    Found = True
                                    break
                if not Found:
                    dateList.append(0)
            return jsonify({"rspCode": 20, "dateList": dateList})                                                                         #成功取得
        else:
            return jsonify({"rspCode": 50})                                                                                               #權限不符
    else:
        return jsonify({"rspCode": 31})                                                                                                 #method使用錯誤

#取得當日行事曆
@Calendar.route('/one_date_list', methods=['POST'])
def one_date_list():
    if request.method == 'POST':
        if session.get('userType') == userType['USER']:
            try:
                value = request.get_json()
            except:
                return jsonify({"rspCode": 40})                                                                          #非法文字
            show_year = value['year']
            show_month = value['month']
            show_day = value['day']
            userID = session.get('userID')
            try:
                query_data = account.query.filter_by(userID = userID).first()
                if query_data == None:
                    return jsonify({"rspCode": 41})                                                                      #userID錯誤，沒有該user
            except:
                return jsonify({"rspCode": 30})                                                                          #資料庫錯誤
            taskList = []
            dateStart = datetime.datetime(show_year, show_month, show_day, 0, 0, 0)
            dateEnd = datetime.datetime(show_year, show_month, show_day, 23, 59, 59)
            for task in query_data.taskSR:
                if task.taskStatus != 4 and task.taskStatus != 11 and task.taskStatus != 12:
                    if dateStart > task.taskStartTime and dateStart < task.taskEndTime:
                        taskList.append(task)
                    elif dateEnd > task.taskStartTime and dateEnd < task.taskEndTime:
                        taskList.append(task)
                    elif dateStart < task.taskStartTime and dateEnd > task.taskStartTime:
                        taskList.append(task)
                    elif dateStart < task.taskStartTime and dateEnd > task.taskEndTime:
                        taskList.append(task)
            for taskCandidate_ in query_data.db_account_taskCandidate:
                #還在申請中
                if taskCandidate_.task.taskStatus == 1:
                    if dateStart > taskCandidate_.task.taskStartTime and dateStart < taskCandidate_.task.taskEndTime:
                        taskList.append(taskCandidate_.task)
                    elif dateEnd > taskCandidate_.task.taskStartTime and dateEnd < taskCandidate_.task.taskEndTime:
                        taskList.append(taskCandidate_.task)
                    elif dateStart < taskCandidate_.task.taskStartTime and dateEnd > taskCandidate_.task.taskStartTime:
                        taskList.append(taskCandidate_.task)
                    elif dateStart < taskCandidate_.task.taskStartTime and dateEnd > taskCandidate_.task.taskEndTime:
                        taskList.append(taskCandidate_.task)
                #已經接到或是完成
                elif taskCandidate_.task.taskStatus > 1 and taskCandidate_.task.taskStatus != 4 and taskCandidate_.task.taskStatus != 11 and taskCandidate_.task.taskStatus != 12:
                    #確定SP是自己
                    if taskCandidate_.task.SP[0].userID == userID:
                        if dateStart > taskCandidate_.task.taskStartTime and dateStart < taskCandidate_.task.taskEndTime:
                            taskList.append(taskCandidate_.task)
                        elif dateEnd > taskCandidate_.task.taskStartTime and dateEnd < taskCandidate_.task.taskEndTime:
                            taskList.append(taskCandidate_.task)
                        elif dateStart < taskCandidate_.task.taskStartTime and dateEnd > taskCandidate_.task.taskStartTime:
                            taskList.append(taskCandidate_.task)
                        elif dateStart < taskCandidate_.task.taskStartTime and dateEnd > taskCandidate_.task.taskEndTime:
                            taskList.append(taskCandidate_.task)

app/views/USER.py
#coding:utf-8
from flask import Blueprint, render_template, session, url_for, redirect
from ..models import userType, db
from ..models.model import account

USER = Blueprint('USER', __name__)

#點數紀錄
@USER.route('/pointRecord')
def point_record():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/point.html')
    else:
        return redirect(url_for('USER.index'))

#忘記密碼頁面
@USER.route('/forgotPassword')
def forgot_password():
    return render_template('/USER/forgotPasswordUser.html')

#輸入新密碼頁面
@USER.route('/resetPassword/<token>')
def reset_password(token):
    return render_template('/USER/resetPasswordUser.html')

#登入頁面
@USER.route('/login')
def login():
    return redirect(url_for('USER.index'))

#註冊頁面
@USER.route('/register')
def register():
    return render_template('/USER/register.html')

#設定頁面
@USER.route('/setting')
def setting():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/setting.html')
    else:
        return redirect(url_for('USER.index'))

#點數申請
@USER.route('/application')
def application():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/application.html', userID=session.get('userID'))
    else:
        return redirect(url_for('USER.index'))

#行事曆
@USER.route('/calendar')
def calendar():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/calendar.html')
    else:
        return redirect(url_for('USER.index'))

#SP - 個人介面 - 雇員評分
@USER.route('/SP/myself/<userID>')
def SP_myself(userID):
    if session.get('userType') == userType['USER']:
        return render_template('/USER/myselfSP.html')
    else:
        return redirect(url_for('USER.index'))

#SR - 個人介面 - 雇員評分
@USER.route('/SR/myself/<userID>')
def SR_myself(userID):
    if session.get('userType') == userType['USER']:
        return render_template('/USER/myselfSR.html')
    else:
        return redirect(url_for('USER.index'))

#評分
@USER.route('/rating')
def rating():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/rating.html')
    else:
        return redirect(url_for('USER.index'))

#入口網站
@USER.route('/')
def index():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/homepage.html')
    else:
        return render_template('/USER/portal.html')

#承接任務頁面
@USER.route('/allTask')
def all_task():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/allTask.html')
    else:
        return redirect(url_for('USER.index'))

#SP - 審核中頁面
@USER.route('/SP/allTaskChecking')
def SP_all_task_checking():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/allTaskSPChecking.html')
    else:
        return redirect(url_for('USER.index'))
    

#SP - 已通過頁面
@USER.route('/SP/allTaskPassed')
def SP_all_task_passed():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/allTaskSPPassed.html')
    else:
        return redirect(url_for('USER.index'))

#SP - 歷史紀錄頁面
@USER.route('/SP/allTaskRecord')
def SP_all_task_record():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/allTaskSPRecord.html')
    else:
        return redirect(url_for('USER.index'))

#SP - 遭拒絕頁面
@USER.route('/SP/allTaskRefused')
def SP_all_task_refused():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/allTaskSPRefused.html')
    else:
        return redirect(url_for('USER.index'))

#SR - 已接受頁面
@USER.route('/SR/allTaskAccepted')
def SR_all_task_accepted():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/allTaskSRAccepted.html')
    else:
        return redirect(url_for('USER.index'))

#SR - 已發布頁面
@USER.route('/SR/allTaskPassed')
def SR_all_task_passed():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/allTaskSRPassed.html')
    else:
        return redirect(url_for('USER.index'))

#SR - 歷史紀錄頁面
@USER.route('/SR/allTaskRecord')
def SR_all_task_record():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/allTaskSRRecord.html')
    else:
        return redirect(url_for('USER.index'))

#新增任務
@USER.route('/createTask')
def create_task():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/createTask.html')
    else:
        return redirect(url_for('USER.index'))

#個人頁面
@USER.route('/info/<userID>')
def info(userID):
    if session.get('userType') == userType['USER']:
        try:
            query_data = account.query.filter_by(userID = int(userID)).first()
        except:
            return "資料庫錯誤"
        if query_data:
            return render_template('/USER/myselfTask.html')
        else:
            return redirect(url_for('USER.info', userID = session.get('userID')))
    else:
        return redirect(url_for('USER.index'))

#所有通知頁面
@USER.route('/notice')
def notice():
    if session.get('userType') == userType['USER']:
        return render_template('/USER/notification.html')
    else:
        return redirect(url_for('USER.index'))

app/views/point.py
from flask import Blueprint
from ..models.model import *

Point = Blueprint('point', __name__)

app/views/portal.py
from flask import Blueprint
from ..models.model import *

Portal = Blueprint('portal', __name__)

app/templates/USER/allTaskSPChecking.html
<!DOCTYPE html>
<html lang="zh-TW">
    <head>
        <title>審核中</title>

        <meta charset="utf-8" />
        <meta name="keywords" content="TimeBank, 時間銀行, 交換服務" />
        <meta name="description" content="時間銀行以交換服務的時數為概念，不再以金錢，而是以時數衡量工作的價值，人人每日都有平等的24小時，如何善用有限的時間，將成為關鍵。" />
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        
        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/navbarUser.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/allTaskSPChecking.css')}}" type="text/css">
    </head>
    <body>
        <header id="userNavbar"></header>
        <div class="bodyContain">
            <div id="tabsFirst">
                <a id="addTask" href="{{url_for('USER.create_task')}}"><div>新增任務</div></a>
                <a id="takeTask" href="{{url_for('USER.all_task')}}"><div>承接任務</div></a>
            </div>
            <div id="tabsSecond">  
                <a id="boss" href="{{url_for('USER.SR_all_task_passed')}}"><div>雇主</div></a>
                <div id="employee">雇員</div>
            </div>    
            <div id="tabsThird">
                <ul>
                    <a href="/USER/SP/allTaskPassed"><li class="notThisPage">已通過</li></a>
                    <li id="thisPage">審核中</li>
                    <a href="{{url_for('USER.SP_all_task_refused')}}"><li class="notThisPage">遭拒絕</li></a>
                    <a href="{{url_for('USER.SP_all_task_record')}}"><li class="notThisPage">歷史紀錄</li></a>
                </ul>
            </div>
            <div id="employeeCheck">
                <table id="eCheck">
                    <tr><td>系統狀態：<span id="systemPrompt"></span></td></tr>
                </table>
            </div>
            <div class="formPage">
                <button class="pageButton" id="prePageButton" onclick="computePage(1)">上一頁</button>
                <span class="formPageNumber" id="pageNumber">1/1</span>
                <button class="pageButton" id="nextPageButton" onclick="computePage(2)">下一頁</button>
            </div>
        </div>
        <footer id="footer"></footer>
        <script src="{{url_for('static', filename='js/footer.js')}}"></script>
        <script src="{{url_for('static', filename='js/clickToSpan.js')}}"></script>
        <script src="{{url_for('static', filename='js/navbarUser.js')}}"></script>
        <script src="{{url_for('static', filename='js/allTaskSPChecking.js')}}"></script>
    </body>
</html>

app/templates/USER/allTaskSPPassed.html
<!DOCTYPE html>
<html lang="zh-TW">
    <head>
        <title>已通過</title>

        <meta charset="utf-8" />
        <meta name="keywords" content="TimeBank, 時間銀行, 交換服務" />
        <meta name="description" content="時間銀行以交換服務的時數為概念，不再以金錢，而是以時數衡量工作的價值，人人每日都有平等的24小時，如何善用有限的時間，將成為關鍵。" />
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        
        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/navbarUser.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/allTaskSPPassed.css')}}" type="text/css">
    </head>
    <body>
        <header id="userNavbar"></header>
        <div class="bodyContain">
            <div id="tabsFirst">
                <a id="addTask" href="{{url_for('USER.create_task')}}"><div>新增任務</div></a>
                <a id="takeTask" href="{{url_for('USER.all_task')}}"><div>承接任務</div></a>
            </div>
            <div id="tabsSecond">  
                <a id="boss" href="{{url_for('USER.SR_all_task_passed')}}"><div>雇主</div></a>
                <div id="employee">雇員</div>
            </div>    
            <div id="tabsThird">
                <ul>
                    <li id="thisPage">已通過</li>
                    <a href="{{url_for('USER.SP_all_task_checking')}}"><li class="notThisPage">審核中</li></a>
                    <a href="{{url_for('USER.SP_all_task_refused')}}"><li class="notThisPage">遭拒絕</li></a>
                    <a href="{{url_for('USER.SP_all_task_record')}}"><li class="notThisPage">歷史紀錄</li></a>
                </ul>
            </div>
            <div id="employeePassed">
                <table id="ePass">
                    <tr><td>系統狀態：<span id="systemPrompt"></span></td></tr>
                </table><br>
                <div id="rating">
                    <div class="formLine" id="rateStar">
                        <div class="formLabelDiv" id="rateStar1">
                            <label for="rate" class="formLabel">評分：</label>
                        </div>
                        <div class="rating">
                            <input type="radio" id="star5" name="rating" value="5" hidden/>
                            <label for="star5"></label>
                            <input type="radio" id="star4" name="rating" value="4" hidden/>
                            <label for="star4"></label>
                            <input type="radio" id="star3" name="rating" value="3" hidden/>
                            <label for="star3"></label>
                            <input type="radio" id="star2" name="rating" value="2" hidden/>
                            <label for="star2"></label>
                            <input type="radio" id="star1" name="rating" value="1" hidden/>
                            <label for="star1"></label>
                        </div>
                    </div>
                    <div class="formLine" id="commentStar">
                        <div class="formLabelDiv" id="commentStar1"><label for="commemt" class="formLabel">評論：</label></div>
                        <div class="formLabelDiv" id="commentStar2">
                            <textarea id="comment" placeholder="請寫下你的評論..."></textarea>
                        </div>     
                    </div>
                    <div class="formLine" id="formComment">
                        <input type="submit" class="formButton" value="送出評論" onclick="sendGrade()" />
                        <input type="button" class="formButton" value="取消" onclick="hideRating()" />
                    </div>
                </div>
            </div>
            <div class="formPage">
                <button class="pageButton" id="prePageButton" onclick="computePage(1)">上一頁</button>
                <span class="formPageNumber" id="pageNumber">1/1</span>
                <button class="pageButton" id="nextPageButton" onclick="computePage(2)">下一頁</button>
            </div>
        </div>
        <footer id="footer"></footer>
        <script src="{{url_for('static', filename='js/footer.js')}}"></script>
        <script src="{{url_for('static', filename='js/clickToSpan.js')}}"></script>
        <script src="{{url_for('static', filename='js/navbarUser.js')}}"></script>
        <script src="{{url_for('static', filename='js/allTaskSPPassed.js')}}"></script>
    </body>
</html>

app/templates/USER/allTaskSPRecord.html
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <title>歷史紀錄</title>

    <meta charset="utf-8" />
    <meta name="keywords" content="TimeBank, 時間銀行, 交換服務" />
    <meta name="description" content="時間銀行以交換服務的時數為概念，不再以金錢，而是以時數衡量工作的價值，人人每日都有平等的24小時，如何善用有限的時間，將成為關鍵。" />
    <meta name="author" content="Ariel Damian Ellen" />
    <meta name="generator" content="VScode 1.47, Sublime Text 3" />
    <meta name="dcterms.rightHolder" content="TaiPay" />
    <meta name="dcterms.dateCopyrighted" content="2020" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

    <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}" type="text/css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/navbarUser.css')}}" type="text/css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/allTaskSPRecord.css')}}" type="text/css">
</head>
    <body>
        <header id="userNavbar"></header>
        <div class="bodyContain">
            <div id="tabsFirst">
                <a id="addTask" href="{{url_for('USER.create_task')}}"><div>新增任務</div></a>
                <a id="takeTask" href="{{url_for('USER.all_task')}}"><div>承接任務</div></a>
            </div>
            <div id="tabsSecond">  
                <a id="boss" href="{{url_for('USER.SR_all_task_passed')}}"><div>雇主</div></a>
                <div id="employee">雇員</div>
            </div>    
            <div id="tabsThird">
                <ul>
                    <a href="{{url_for('USER.SP_all_task_passed')}}"><li class="notThisPage">已通過</li></a>
                    <a href="{{url_for('USER.SP_all_task_checking')}}"><li class="notThisPage">審核中</li></a>
                    <a href="{{url_for('USER.SP_all_task_refused')}}"><li class="notThisPage">遭拒絕</li></a>
                    <li id="thisPage">歷史紀錄</li>
                </ul>
            </div>
            <div id="employeeRecord">
                <table id="eRecord">
                    <tr><td>系統狀態：<span id="systemPrompt"></span></td></tr>
                </table>
                <div id="reportDiv">
                    <tr><td>
                        <textarea id="reportReason" placeholder="請輸入檢舉原因..."></textarea>
                        <div class="button" onclick="hideReportDiv()">取消</div>
                        <div class="button" onclick="sendReport()">送出檢舉</div>
                    </td></tr>
                </div>
            </div>
            <div class="formPage">
                <button class="pageButton" id="prePageButton" onclick="computePage(1)">上一頁</button>
                <span class="formPageNumber" id="pageNumber">1/1</span>
                <button class="pageButton" id="nextPageButton" onclick="computePage(2)">下一頁</button>
            </div>
            
        </div>
        <footer id="footer"></footer>
        <script src="{{url_for('static', filename='js/footer.js')}}"></script>
         <script src="{{url_for('static', filename='js/clickToSpan.js')}}"></script>
        <script src="{{url_for('static', filename='js/navbarUser.js')}}"></script>
        <script src="{{url_for('static', filename='js/allTaskSPRecord.js')}}"></script>
    </body>
</html>

app/templates/USER/allTaskSPRefused.html
<!DOCTYPE html>
<html lang="zh-TW">
    <head>
        <title>遭拒絕</title>

        <meta charset="utf-8" />
        <meta name="keywords" content="TimeBank, 時間銀行, 交換服務" />
        <meta name="description" content="時間銀行以交換服務的時數為概念，不再以金錢，而是以時數衡量工作的價值，人人每日都有平等的24小時，如何善用有限的時間，將成為關鍵。" />
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        
        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/navbarUser.css')}}" type="text/css">
        <link rel="stylesheet" href="{{url_for('static', filename='css/allTaskSPRefused.css')}}" type="text/css">

    </head>

    <body>
        <header id="userNavbar"></header>
        <div class="bodyContain">
            <div id="tabsFirst">
                <a id="addTask" href="{{url_for('USER.create_task')}}"><div>新增任務</div></a>
                <a id="takeTask" href="{{url_for('USER.all_task')}}"><div>承接任務</div></a>
            </div>
            <div id="tabsSecond">  
                <a id="boss" href="{{url_for('USER.SR_all_task_passed')}}"><div>雇主</div></a>
                <div id="employee">雇員</div>
            </div>    
            <div id="tabsThird">
                <ul>
                    <a href="{{url_for('USER.SP_all_task_passed')}}"><li class="notThisPage">已通過</li></a>
                    <a href="{{url_for('USER.SP_all_task_checking')}}"><li class="notThisPage">審核中</li></a>
                    <li id="thisPage">遭拒絕</li>
                    <a href="{{url_for('USER.SP_all_task_record')}}"><li class="notThisPage">歷史紀錄</li></a>
                </ul>
            </div>
            <div id="employeeRefused">
                <table id="eRefused">
                    <tr><td>系統狀態：<span id="systemPrompt"></span></td></tr>
                </table>
            </div>
            <div class="formPage">
                <button class="pageButton" id="prePageButton" onclick="computePage(1)">上一頁</button>
                <span class="formPageNumber" id="pageNumber">1/1</span>
                <button class="pageButton" id="nextPageButton" onclick="computePage(2)">下一頁</button>
            </div>
        </div>
        <footer id="footer"></footer>
        <script src="{{url_for('static', filename='js/footer.js')}}"></script>
        <script src="{{url_for('static', filename='js/clickToSpan.js')}}"></script>
        <script src="{{url_for('static', filename='js/navbarUser.js')}}"></script>
        <script src="{{url_for('static', filename='js/allTaskSPRefused.js')}}"></script>
    </body>
</html>

app/templates/USER/notification.html
<!DOCTYPE html>
<html lang="zh-TW">
    <head>
        <title>通知</title>

        <meta charset="utf-8" />
        <meta name="keywords" content="TimeBank, 時間銀行, 交換服務" />
        <meta name="description" content="時間銀行以交換服務的時數為概念，不再以金錢，而是以時數衡量工作的價值，人人每日都有平等的24小時，如何善用有限的時間，將成為關鍵。" />
        <meta name="author" content="Ariel Damian Ellen" />
        <meta name="generator" content="VScode 1.47, Sublime Text 3" />
        <meta name="dcterms.rightHolder" content="TaiPay" />
        <meta name="dcterms.dateCopyrighted" content="2020" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        
        <link rel="stylesheet" href="{{url_for('static', filename='css/common.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/navbarUser.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename='css/notification.css')}}">

    </head>
    <body>
        <header id="userNavbar"></header>
        <div class="bodyContainer">
            <div class="notificationPart">
                <table id="notificationTable">
                    <caption id="tableTitle">通知歷史紀錄</caption>
                    <tr><td>
                        <div class="introduction">尚無通知</div>
                    </td></tr>
                </table>
            </div>
            <div class="formPage">
                <button class="pageButton" id="prePageButton" onclick="computePage(1)">上一頁</button>
                <span class="formPageNumber" id="pageNumber">1/1</span>
                <button class="pageButton" id="nextPageButton" onclick="computePage(2)">下一頁</button>
            </div>
        </div>
    </body>
    <footer id="footer"></footer>
    <script src="{{url_for('static', filename='js/footer.js')}}"></script>
    <script src="{{url_for('static', filename='js/clickToSpan.js')}}"></script>
    <script src="{{url_for('static', filename='js/navbarUser.js')}}"></script>
    <script src="{{url_for('static', filename='js/notice.js')}}"></script>
</html>